import type { Metadata } from "next";
// 1. Tambahkan DM_Sans di baris import ini
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Inisialisasi DM Sans sesuai ketebalan (weight) dari Figma
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App", // Nanti bisa kamu ganti jadi "AI For Impact 2026"
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // 3. Sisipkan variabel dmSans di dalam className html
      className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      {/* 4. Terapkan dmSans.className ke body agar seluruh teks default ke DM Sans */}
      <body
        className={`min-h-full flex flex-col ${dmSans.className}`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
