import type { Metadata } from "next";
import { JetBrains_Mono, Science_Gothic } from "next/font/google";
import "./globals.css";

// Headings. Variable font — weight is driven by font-weight utilities.
const scienceGothic = Science_Gothic({
  variable: "--font-science-gothic",
  subsets: ["latin"],
  // Science Gothic postdates Next's bundled capsize metrics table, so it has no
  // precalculated fallback overrides. Opting out skips a lookup that always
  // fails (and logs); the explicit stack is what actually covers the swap.
  fallback: ["Arial", "sans-serif"],
  adjustFontFallback: false,
});

// Sub-headings and body.
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI For Impact 2026",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${scienceGothic.variable} ${jetbrainsMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
